.\" Process this file with
.\" groff -man -Tascii clone-all.1
.\"
.TH "KEGGER" 1 "APRIL 2014" Unix "User Manuals"
.SH "NAME"
\fBkegger\fR \- Automated install of Homebrew Casks
.SH SYNOPSIS
\fBkegger\fR  \-\-version
.br
\fBkegger\fR  [options] \fI<keg>\fR
.SH DESCRIPTION
Automates the installation of Homebrew Casks. When passed a valid keg, (via the Github's Gist ID), \fBkegger\fR will download and install all casks as well as upgrade any existing casks. See below for a valid keg file.
.SH KEG FILE
A keg file is simply a text file where each cask to be installed is on a separate line.
.SS Example .keg file
.RS 0
alfred
.RS 0
dropbox
.RS 0
rdio
.SH RETURN VALUES
The following exit codes are possible:
.IP "\fb0\fR"
success
.IP "\fb1\fR"
general error, typically a bad flag or value
.IP "\fb2\fR"
missing dependency error
.IP "\fb3\fR"
invalid or missing Github Gist id
.SH REPORTING BUGS
.RI "Report bugs to the Github repository <" "https://github.com/iamnewton/kegger/issues" ">"
.SH AUTHOR
.RI "Newton
